groups:
- name: exim
  rules:
  - alert: mail_roundtrip
    expr: mail_roundtrip_up != 1 or absent(mail_roundtrip_up)
    for: 10m
    annotations:
      summary: Email roundtrip failed
  - alert: caldav_roundtrip
    expr: mail_caldav_roundtrip_up != 1 or absent(mail_caldav_roundtrip_up)
    for: 10m
    annotations:
      summary: Caldav roundtrip failed