route:
  receiver: blackhole
  group_by: [alertname]
  routes:
  - receiver: pushover
    match:
      severity: page
  - receiver: email
    match:
      severity: warning

receivers:
  - name: blackhole

  - name: email
    email_configs:
      - to: wosc@wosc.de
        from: wosc+prometheus@wosc.de
        smarthost: localhost:25

  - name: pushover
    pushover_configs:
      - user_key: {{component.pushover_user_key}}
        token: {{component.pushover_api_key}}
        send_resolved: false
