listen:
  port: 9105
  address: 127.0.0.1

namespaces:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
    source_files:
{% for log in component.logfiles %}
      - {{log}}
{% endfor %}
