package "exim4-daemon-heavy"
service "exim4" do
  supports :status => true, :restart => true, :reload => true
end


wosc_mysql_database node["mailserver"]["db_name"]
wosc_mysql_user node["mailserver"]["db_user"] do
  password node["mailserver"]["db_pass"]
end
wosc_mysql_grant node["mailserver"]["db_name"] do
  user node["mailserver"]["db_user"]
end

template "/etc/exim4/schema.sql" do
  source "schema.sql"
end
execute "mailserver_db_schema" do
  command "mysql -Bs -uroot mailserver < /etc/exim4/schema.sql"
  not_if "echo 'show tables' | mysql -uroot mailserver | grep -q ."
end


file "/etc/exim4/update-exim4.conf" do
  content "dc_eximconfig_configtype='none'"
  notifies :run, "execute[update-exim4.conf]"
end
execute "update-exim4.conf" do
  action :nothing
end

directory "/etc/exim4/domains"

link "/etc/exim4/system-filter" do
  to "/home/wosc/.dot/mail/.filter-system"
end
link "/var/mail/wosc@wosc.de/filter" do
  to "/home/wosc/.dot/mail/.filter"
  only_if "ls /var/mail/wosc@wosc.de"
end

template "/etc/aliases" do
  source "aliases"
end
file "/etc/email-addresses" do
  content "wosc: wosc@wosc.de"
end

template "/etc/exim4/exim4.conf" do
  source "exim4.conf"
  notifies :reload, "service[exim4]"
end

directory "/var/mail" do
  group "Debian-exim"
end


package "clamav"
package "clamav-daemon"
service "clamav-daemon"

group "clamav" do
  action :manage
  append true
  members "Debian-exim"
end

directory "/var/spool/exim4/scan" do
  owner "Debian-exim"
  group "clamav"
  mode "0775"
end


package "spamassassin"
package "spamc"
package "libdbi-perl"
package "libdbd-mysql-perl"
package "pyzor"
package "razor"

template "/etc/spamassassin/local.cf" do
  source "spamassassin.conf"
end

directory "/etc/spamassassin/pyzor"
file "/etc/spamassassin/pyzor/servers" do
  content "public.pyzor.org:24441"
end

execute "spamassassin_db_schema1" do
  command "sed -e 's/userpref/sa_pref/' -e 's/TYPE=MyISAM/ENGINE=InnoDB/' /usr/share/doc/spamassassin/sql/userpref_mysql.sql | mysql -Bs -uroot mailserver"
  not_if "echo 'show tables' | mysql -uroot mailserver | grep -q sa_pref"
end
execute "spamassassin_db_schema2" do
  command "cat /usr/share/doc/spamassassin/sql/bayes_mysql.sql | mysql -Bs -uroot mailserver"
  not_if "echo 'show tables' | mysql -uroot mailserver | grep -q bayes_vars"
end
# execute "spamassassin_db_schema3" do
#   command "cat /usr/share/doc/spamassassin/sql/txrep_mysql.sql | sed -e 's/txrep/sa_txrep/' | mysql -Bs -uroot mailserver"
#   not_if "echo 'show tables' | mysql -uroot mailserver | grep -q sa_txrep"
# end

file "/usr/lib/tmpfiles.d/spamassassin.conf" do
  content "# Generated by wosc-mailserver::default\nd /var/run/spamassassin 0755 nobody nogroup"
end
template "/etc/default/spamassassin" do
  source "spamassassin.default"
end

execute "sed -i -e 's/#loadplugin Mail::SpamAssassin::Plugin::DCC/loadplugin Mail::SpamAssassin::Plugin::DCC/' /etc/spamassassin/v310.pre" do
  only_if "grep -q '#loadplugin Mail::SpamAssassin::Plugin::DCC' /etc/spamassassin/v310.pre"
  notifies :restart, "service[spamassassin]", :delayed
end

service "spamassassin" do
  action :enable
end


template "/etc/cron.daily/spam-clean" do
  source "spam-clean.sh"
  mode "0755"
end
template "/etc/cron.daily/spam-learn" do
  source "spam-learn.sh"
  mode "0755"
end
# template "/etc/cron.weekly/spam-awl" do
#   source "spam-awl.sh"
#   mode "0755"
# end


package "courier-imap-ssl"
service "courier-imap-ssl"
package "courier-authlib-mysql"
service "courier-authdaemon"

group "courier" do
  action :manage
  append true
  members "Debian-exim"
end

template "/etc/courier/authdaemonrc" do
  source "courier/authdaemonrc"
  owner "daemon"
  group "daemon"
  mode "0660"
  notifies :restart, "service[courier-authdaemon]", :delayed
end
template "/etc/courier/authmysqlrc" do
  source "courier/authmysqlrc"
  owner "daemon"
  group "daemon"
  mode "0660"
  notifies :restart, "service[courier-authdaemon]", :delayed
end

template "/etc/courier/imapd-ssl" do
  source "courier/imapd-ssl"
  notifies :restart, "service[courier-imap-ssl]"
end

package "socat"
template "/usr/local/bin/authdaemon-test" do
  source "courier/authdaemon-test"
  mode "0755"
end
