#!/bin/bash

mkdir -p /var/lib/mysql-backup/current
umask 177  # create backup files with 0600

# Dump each database into a file
databases=$(echo "show databases" | mysql -uroot --silent | \
    grep -v "^\(information_schema\|performance_schema\|sys\)$")
for db in $databases; do
    output="/var/lib/mysql-backup/current/$db.sql"
    mysqldump --add-drop-database --databases $db > $output
done

# Bundle all database files together under current timestamp
now=$(date +%Y-%m-%dT%H-%M-%S)
tar cfz /var/lib/mysql-backup/mysql-backup-$now.tar.gz --absolute-names \
    --transform "s+^/var/lib/mysql-backup/current+mysql-backup-$now+" \
    /var/lib/mysql-backup/current
rm -rf /var/lib/mysql-backup/current

# Clean up old tarballs
find  /var/lib/mysql-backup -name "mysql-backup-*.tar.gz" -mtime +7 | xargs rm -f
