package "supervisor"
service "supervisor" do
  supports :status => true, :restart => true, :reload => true
  action :enable
end

link "/usr/local/bin/sv" do
  to "/usr/bin/supervisorctl"
end

file "/usr/lib/tmpfiles.d/supervisor.conf" do
  content "# Generated by wosc-fastcgi::supervisor\nd /var/run/supervisor 0755 root root"
end

group "supervisor"

template "/etc/supervisor/supervisord.conf" do
  source "supervisord.conf"
  notifies :restart, "service[supervisor]", :delayed
end

execute "reload_supervisor" do
  action :nothing
  command "supervisorctl reread; supervisorctl update"
end
