#!/bin/bash

email="wosc@wosc.de"

cd ~/data
for domain in */; do
    domain=$(basename $domain)
    cd ~/data/$domain

    ~/deployment/bin/simp_le --email $email --vhost $domain:~/public/$domain \
        --reuse_key -f key.pem -f cert.pem -f fullchain.pem -f account_key.json
    updated=$?
    rm -rf ~/public/$domain/acme-challenge

    if [ "$updated" = "0" ]; then
        if [ -x ./update ]; then
            ./update
        else
            sudo /etc/init.d/nginx reload &> /dev/null
        fi
    fi
done
